@props(['name'])

{{-- @error directive checks sessions error bag for the given $name. Errors are stored there when validation fails. --}}
@error($name)
  {{-- $message is variable generated by @error directive --}}
  <p class="text-red-500">{{ $message }}</p>
@enderror